### ISSUE TITLE
Update opam

### ISSUE THREAD

**Issue by Aaylor** [ocamllabs/ocaml-modular-implicits#31] opened 2015-03-17 18:14 UTC
The modular implicits compiler is not updated on opam.
After a "opam upgrade && opam update", i still have this version : 

```
4.02.1+dev0-2014-08-29
```

Some fixes are not available (as #7)

**Comment by lpw25** [comment] 2015-03-17 18:19
The opam repo is pointed at the head of the branch so it should get you the latest version. However, I don't think that `opam upgrade && opam update` will trigger reinstalls of compilers, you should try `opam switch reinstall 4.02.0+module-implicits` instead.

**Comment by Aaylor** [comment] 2015-03-17 18:26
Even with the reinstallation, my version of modular-implicits compiler stay the same

**Comment by yallop** [comment] 2015-03-17 18:31
The [version string](https://github.com/ocamllabs/ocaml-modular-implicits/blob/ef23094efe4efd645010c3a866f5ea9a1235db2e/VERSION) is out of date, but the compiler itself is up to date.

**Comment by Aaylor** [comment] 2015-03-17 18:43
I still have the same issue with the example in #7

```
➜  rlwrap ocaml -dsource
        OCaml version 4.02.1+dev0-2014-08-29

# let f (implicit M : Map.S)  () = ();;

let f (implicit M : (M : Map.S))  () = ();;
val f : (implicit M : Map.S) -> unit -> unit = <fun>
```

**Comment by yallop** [comment] 2015-03-17 18:46
It's not quite the same: the source printer was previously printing

`let f (implicit M : (M : (module Map.S)))  () = ();;`

but now it's printing

`let f (implicit M : (M : Map.S))  () = ();;`

Feel free to re-open #7, since the printing is still not quite right.  I'm going to close this issue, since the OPAM setup is working as intended.

**Closed as completed by yallop** 2015-03-17 18:46 UTC
